// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK93LKm_z574xbGxt4auZ-ECqrEaA6r3M',
    appId: '1:138098843263:web:29b55802cbcdf2d926694a',
    messagingSenderId: '138098843263',
    projectId: 'academya-fiap-4547a',
    authDomain: 'academya-fiap-4547a.firebaseapp.com',
    storageBucket: 'academya-fiap-4547a.firebasestorage.app',
    measurementId: 'G-DT80FDPS6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWn7jnK-ZiV1_Eg7144z5FppV-YnvGmc0',
    appId: '1:138098843263:android:8496e98895ddb72426694a',
    messagingSenderId: '138098843263',
    projectId: 'academya-fiap-4547a',
    storageBucket: 'academya-fiap-4547a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK93LKm_z574xbGxt4auZ-ECqrEaA6r3M',
    appId: '1:138098843263:web:c7a558ab5b8cd9ef26694a',
    messagingSenderId: '138098843263',
    projectId: 'academya-fiap-4547a',
    authDomain: 'academya-fiap-4547a.firebaseapp.com',
    storageBucket: 'academya-fiap-4547a.firebasestorage.app',
    measurementId: 'G-N1F1B4NW1M',
  );
}
